name: Publish on GitHub & Modrinth

on:
    push:
        tags: 
          - r-*

permissions:
    contents: write
  
jobs:        
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check Environment Variables
              run: env
    
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  submodules: true
      
            - name: Setup Java
              uses: actions/setup-java@v2
              with:
                  distribution: "temurin"
                  java-version: ${{vars.JAVA_VERSION}}

            - name: Make Gradle Wrapper Executable
              if: ${{ runner.os != 'Windows' }}
              run: chmod +x ./gradlew
            
            - name: Build
              run: ./gradlew clean build
            
            - name: Publish (Modrinth/GitHub)
              uses: Kir-Antipov/mc-publish@v3.2
              with:
                  modrinth-id: bYwHgKTK
                  modrinth-token: ${{secrets.MODRINTH_TOKEN}}
                
                  name: "NUB's QoL Mods ${{github.ref_name}}-${{vars.MINECRAFT_VERSION}}"
                  version: "${{env.VERSION}}"
                  version-type: release
                  changelog-file: CHANGELOG.md
                
                  loaders: fabric
                  game-versions: "${{env.MINECRAFT_VERSION}}"
                  java: ${{vars.JAVA_VERSION}}
